// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsvmvbqnfvrsdmpljeeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzdm12YnFuZnZyc2RtcGxqZWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDA1MTUsImV4cCI6MjA2Nzg3NjUxNX0.j5hwDUiFtKYs4HaGYJ_BCWq0869ge3kwDAqZIppQmvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});